apiVersion: v1
kind: Service
metadata:
  name: kv-raft
  labels:
    app: SisyphusDB
spec:
  ports:
    - port: 5001
      name: raft-rpc
    - port: 8001
      name: http-api
  clusterIP: None #makes this a headless server for StatefulSets
  selector:
    app: SisyphusDB

---
apiVersion: v1
kind: Service
metadata:
  name: kv-public
  labels:
    app: SisyphusDB
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8001
      nodePort: 30000 # access point
      name: http-api
  selector:
    app: SisyphusDB

